### ISSUE TITLE
chore(dep): migrate to `pnpm` 

### ISSUE THREAD

**Issue by priyankarpal** [AlphaDecodeX/NoMise_Store#24]
hey, @AlphaDecodeX we are using `npm` for this project right now. We can migrate from `npm` to `pnpm` for package management. 

## Why `pnpm`?

- `pnpm` offers improved performance
- reduced disk space usage and better compatibility with existing `npm` and `Yarn` 
- making it a superior choice for managing dependencies efficiently.

## What do we need to do?
- remove `node_modules`
- install `pnpm`
- test in local
- change documentation

 ### if you want you can assign me

**Comment by AlphaDecodeX** [comment]
Got it @priyankarpal, I am assigning this to you. Kindly create a branch and PR. Thanks for the suggestion 🚀

**Comment by priyankarpal** [comment]
Completed.
