### ISSUE TITLE
feat : Add PageNotFound page for wrong URL handling

### ISSUE THREAD

**Issue by Saurav-Pant** [AlphaDecodeX/NoMise_Store#27]
When a user enters the wrong URL on the website, currently it shows nothing. I believe it would be beneficial to add a PageNotFound page to handle such cases and provide a better user experience. If you agree, I would like to take ownership of this task and work on implementing the PageNotFound page.

Please assign this issue to me so I can start working on it. 

https://github.com/AlphaDecodeX/NoMise_Store/assets/103263909/7ef92c00-6dc5-47d2-b427-2c45ba4da919

**Comment by AlphaDecodeX** [comment]
@Saurav-Pant Assigned buddy 🚀 You can work on this
