### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by priyankarpal** [AlphaDecodeX/NoMise_Store#3]
* Add contribution guide
* add workflows
* add  issue, PR templates
* add Branch protection rules

**Comment by AlphaDecodeX** [comment]
> * Add contribution guide
> * add workflows
> * add  issue, PR templates
> * add Branch protection rules

Will do soon.

**Comment by AlphaDecodeX** [comment]
> * Add contribution guide
> * add workflows
> * add  issue, PR templates
> * add Branch protection rules

Thanks for pointing out

**Comment by AlphaDecodeX** [comment]
@priyankarpal Which is pending out of these ?

**Comment by priyankarpal** [comment]
workflows I will add
