### ISSUE TITLE
add code of conduct 

### ISSUE THREAD

**Issue by priyankarpal** [AlphaDecodeX/NoMise_Store#33]
We need to add a code of conduct to establish clear guidelines for expected behaviour and ensure a respectful and inclusive environment for all participants.

**Comment by AlphaDecodeX** [comment]
✅

**Comment by AlphaDecodeX** [comment]
@priyankarpal I have never used Github before. Was used to with bitbucket. Thanks for the contribution as I never knew about Issue_templates, code_of_conduct etc

**Comment by priyankarpal** [comment]
> @priyankarpal I have never used Github before. Was used to with bitbucket. Thanks for the contribution as I never knew about Issue_templates, code_of_conduct etc

ok
