### ISSUE TITLE
add security policy

### ISSUE THREAD

**Issue by priyankarpal** [AlphaDecodeX/NoMise_Store#34]
@AlphaDecodeX please add a security policy it helps to understand which version is stable & which one is not

**Comment by AlphaDecodeX** [comment]
✅

**Comment by priyankarpal** [comment]
you need to add it. you know the stable version

**Comment by AlphaDecodeX** [comment]
@priyankarpal We haven't released yet. So, It is not possible now

**Comment by priyankarpal** [comment]
ok ok
