### ISSUE TITLE
Search Button is not Working

### ISSUE THREAD

**Issue by bharathkalyans** [AlphaDecodeX/NoMise_Store#4]
- After searching for a product and once clicking on it, it is not taking me to the products/{productId} page.
- Guess the functionality is not implemented or it might have been broken.

<img width="1440" alt="Screenshot 2023-05-08 at 2 13 59 PM" src="https://user-images.githubusercontent.com/49526472/236779145-a150b963-4462-4300-9e86-974298abd377.png">

**Comment by AlphaDecodeX** [comment]
It is working Now, Earlier its logic was not implemented
